Repository mahammad-mostafa/tesla-booking-back-end, pull requests merged in 2024-01, with the labels that each got.

#12 Feature/project setup ⚙️
  .dockerignore
  .gitattributes
  .github/workflows/linters.yml
  .gitignore
  .rubocop.yml
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
  README.md
  Rakefile
  app/channels/application_cable/channel.rb
  app/channels/application_cable/connection.rb
  app/controllers/application_controller.rb
  app/controllers/concerns/.keep
  app/jobs/application_job.rb
  app/mailers/application_mailer.rb
  app/models/application_record.rb
  app/models/concerns/.keep
  app/views/layouts/mailer.html.erb
  app/views/layouts/mailer.text.erb
  bin/bundle
  bin/bundle.cmd
  bin/docker-entrypoint
  bin/rails
  bin/rake
  bin/setup
  config.ru
  config/application.rb
  config/boot.rb
  config/cable.yml
  config/credentials.yml.enc
  config/database.yml
  config/environment.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/cors.rb
  config/initializers/filter_parameter_logging.rb
  config/initializers/inflections.rb
  config/locales/en.yml
  config/puma.rb
  config/routes.rb
  config/storage.yml
  db/seeds.rb
  lib/tasks/.keep
  log/.keep
  public/robots.txt
  storage/.keep
  test/channels/application_cable/connection_test.rb
  test/controllers/.keep
  test/fixtures/files/.keep
  test/integration/.keep
  test/mailers/.keep
  test/models/.keep
  test/test_helper.rb
  tmp/.keep
  tmp/pids/.keep
  tmp/storage/.keep
  vendor/.keep
Labels: enhancement, project setup

#15 Feature Reservation Model and Controller
  app/controllers/api/v1/cars_controller.rb
  app/controllers/api/v1/reservations_controller.rb
  app/controllers/api/v1/users/sessions_controller.rb
  app/controllers/application_controller.rb
  app/helpers/jwt_helper.rb
  app/models/car.rb
  app/models/performance_detail.rb
  app/models/reservation.rb
  app/models/user.rb
  config/routes.rb
  db/migrate/20240124154549_create_cars.rb
  db/migrate/20240124154917_create_performance_details.rb
  db/migrate/20240125082153_create_reservations.rb
  db/schema.rb
  db/seeds.rb
  test/controllers/api/v1/cars_controller_test.rb
  test/controllers/api/v1/reservations_controller_test.rb
  test/fixtures/cars.yml
  test/fixtures/performance_details.yml
  test/fixtures/reservations.yml
  test/models/car_test.rb
  test/models/performance_detail_test.rb
  test/models/reservation_test.rb
Labels: API-Models, API-EndPoints, API-Controllers

#14 Feature: Car model and controller 🎫
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/cars_controller.rb
  app/models/car.rb
  app/models/performance_detail.rb
  db/migrate/20240128105512_add_owned_by_user_to_cars.rb
  db/schema.rb
  db/seeds.rb
Labels: enhancement, API-Models, API-EndPoints, API-Controllers

#16 Hotfix/fix car deletion without token 💯
  app/controllers/api/v1/cars_controller.rb
  db/schema.rb
Labels: Hot fix

#17 Feature: Render deployment
  app/helpers/jwt_helper.rb
  bin/render-build.sh
  config/credentials.yml.enc
  config/database.yml
  config/environments/production.rb
  render.yaml
Labels: enhancement, deployment

#18 Hotfix: fix json structure
  app/controllers/api/v1/cars_controller.rb
  app/controllers/api/v1/reservations_controller.rb
  app/controllers/api/v1/users/registrations_controller.rb
  app/controllers/api/v1/users/sessions_controller.rb
  db/seeds.rb
Labels: Hot fix

#19 Hotfix: Update reservation json structure
  app/controllers/api/v1/reservations_controller.rb
Labels: Hot fix
