Repository mahammad-mostafa/tesla-booking-back-end, pull requests merged in 2024-02, with the labels that each got.

#20 Feature/api documentation 📚
  .rspec
  .rubocop.yml
  Gemfile
  Gemfile.lock
  config/initializers/rswag_api.rb
  config/initializers/rswag_ui.rb
  config/routes.rb
  spec/rails_helper.rb
  spec/requests/api/v1/cars_spec.rb
  spec/requests/api/v1/reservations_spec.rb
  spec/requests/api/v1/users/registrations_spec.rb
  spec/requests/api/v1/users/sessions_spec.rb
  spec/spec_helper.rb
  spec/swagger_helper.rb
  swagger/v1/swagger.yaml
Labels: documentation, enhancement

#21 Feature/ Final touches
  Backend.png
  ER Diagram.png
  Frontend.png
  LICENSE
  README.md
  swagger/v1/swagger.yaml
Labels: documentation, enhancement, final touches

#23 Docs: Update 'README.md' Documentation
  README.md
Labels: documentation
